name: my-image
channels:
  - conda-forge
dependencies:
  - python=3.14 # if changing, also change in .binder/environment.yml

  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser~=5.0

  # nbgitpuller is very helpful when distributing user content
  - nbgitpuller>=1.2

  # Specify major version of jupyterlab to use. Manually bump it when you want to upgrade
  # jupyterlab version
  - jupyterlab>=4.5

  # This provides memory usage stats on JupyterLab and classic notebook
  - jupyter-resource-usage>=1.2.0

  # gh-scoped-creds allows users to securely push to GitHub from their repo.
  # https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f has
  # some more information
  - gh-scoped-creds>=4.1

  # More git tools from github-cli
  - gh

  # VS Code support
  - jupyter-vscode-proxy
  - code-server

  # Jupyter tools
  - ipython~=8.17
  - ipywidgets>=8.1
  - jupyter-ai~=3.0.0
  - jupyter-offlinenotebook>=0.3

  # Access linux desktop from inside JupyterHub
  - jupyter-remote-desktop-proxy>=3.0
  - jupyter-sshd-proxy>=0.2
  - jupyterlab-favorites>=3.2
  - jupyterlab-geojson>=3.4
  - jupyterlab-git>=0.50
  - jupyterlab-h5web~=11.1
  - jupyterlab-myst>=2.4
  - jupyterlab_pygments>=0.3
  - jupytext>=1.17
  - mystmd
